packages:
  - apps/*
  - packages/*

catalog:
  '@analogjs/vite-plugin-angular': ^2.1.1
  '@angular/build': ^21.0.1
  '@angular/cli': ^21.0.1
  '@angular/common': ^21.0.1
  '@angular/compiler': ^21.0.1
  '@angular/compiler-cli': ^21.0.1
  '@angular/core': ^21.0.1
  '@angular/platform-browser': ^21.0.1
  '@angular/platform-browser-dynamic': ^21.0.1
  '@sveltejs/vite-plugin-svelte': ^6.2.1
  '@tailwindcss/vite': ^4.1.17
  '@tsconfig/svelte': ^5.0.6
  '@types/node': ^24.10.1
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.1
  '@vitejs/plugin-vue': ^6.0.2
  autoprefixer: ^10.4.22
  effect: ^3.19.8
  next: ^16.0.5
  postcss: ^8.5.6
  react: ^19.2.0
  react-dom: ^19.2.0
  rxjs: ^7.8.2
  svelte: ^5.45.2
  tailwindcss: ^4.1.17
  typescript: ^5.9.3
  vite: ^7.2.4
  vue: ^3.5.25
  vue-tsc: ^3.1.5

catalogs:
  svelte4:
    '@sveltejs/vite-plugin-svelte': ^3.0.0
    '@tsconfig/svelte': ^4.0.0
    svelte: ^4.2.0
    vite: ^5.0.0

verifyDepsBeforeRun: install
